import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-consumer-lending-fee-refund-compliance",
  "engine": "recovery",
  "title": "Consumer Lending Fee Refund Compliance",
  "shortTitle": "Consumer Lending Fee Refund Compliance",
  "tagline": "Identify unsupported consumer fees, calculate refunds and interest, and govern notices, remediation, and regulator evidence.",
  "industry": "Consumer Finance Compliance",
  "buyer": "Banks, fintech lenders, and servicers",
  "uiPort": 4680,
  "apiPort": 5680,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Consumer Lending Fee Refund Compliance converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices in one accountable workflow. Identify unsupported consumer fees, calculate refunds and interest, and govern notices, remediation, and regulator evidence.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Consumer Lending Fee Refund Compliance evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("product-agreement-library","CLF01","Product agreement library","Execute product agreement library using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed product agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Product agreement library Reference","text","CLF01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("fee-schedule-versioning","CLF02","Fee schedule versioning","Execute fee schedule versioning using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed fee schedule versioning decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Fee schedule versioning Reference","text","CLF02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("account-transaction-ingestion","CLF03","Account transaction ingestion","Execute account transaction ingestion using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed account transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Account transaction ingestion Reference","text","CLF03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("late-fee-validation","CLF04","Late fee validation","Execute late fee validation using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed late fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Late fee validation Reference","text","CLF04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("nsf-fee-sequence-analysis","CLF05","NSF fee sequence analysis","Execute nsf fee sequence analysis using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed nsf fee sequence analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","NSF fee sequence analysis Reference","text","CLF05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("convenience-fee-review","CLF06","Convenience fee review","Execute convenience fee review using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed convenience fee review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Convenience fee review Reference","text","CLF06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("add-on-product-consent","CLF07","Add-on product consent","Execute add-on product consent using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed add-on product consent decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Add-on product consent Reference","text","CLF07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("military-status-protections","CLF08","Military status protections","Execute military status protections using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed military status protections decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Military status protections Reference","text","CLF08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("state-cap-validation","CLF09","State cap validation","Execute state cap validation using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed state cap validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","State cap validation Reference","text","CLF09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("duplicate-fee-detection","CLF10","Duplicate fee detection","Execute duplicate fee detection using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed duplicate fee detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Duplicate fee detection Reference","text","CLF10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("refund-amount-calculation","CLF11","Refund amount calculation","Execute refund amount calculation using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed refund amount calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Refund amount calculation Reference","text","CLF11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("consumer-notice-generation","CLF12","Consumer notice generation","Execute consumer notice generation using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed consumer notice generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Consumer notice generation Reference","text","CLF12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("complaint-linkage","CLF13","Complaint linkage","Execute complaint linkage using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed complaint linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Complaint linkage Reference","text","CLF13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("remediation-payment-tracking","CLF14","Remediation payment tracking","Execute remediation payment tracking using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed remediation payment tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Remediation payment tracking Reference","text","CLF14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]}),
feature("product-fee-analytics","CLF15","Product fee analytics","Execute product fee analytics using loan agreements, fee schedules, transactions, payment history, late fees, NSF fees, add-on products, military status, complaints, refunds, and notices.","Produce a governed product fee analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Product / Consumer Account","text","Product / Consumer Account · Standard Case"],["caseReference","Product fee analytics Reference","text","CLF15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1016250],["supportedAmount","Evidence-Supported Amount","currency",853650],["domainDriver","Fee Category","select","Late fee",["Late fee","NSF fee","Add-on product"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Product agreement library case","Fee schedule versioning case","Account transaction ingestion case","Late fee validation case","NSF fee sequence analysis case"]})
]);
